GITHUB_TOKEN: ENC[AES256_GCM,data:Fy2bkmt61W4dd+1FIXGP5ScoIBBsdcTMx/xbKgIMzvaKu8+997uhD8C/LkoJOwMbcEpUpq621AXhpuP51zMbPZIBde8VDu/RmFvRAVRkhL/196K1QUKYVjrvzKZF,iv:EfWazDjEI4EuGmlLUTf1jkXtIS5zfh7E3uIb/05fnS4=,tag:eDG6tV4tfKDtRTuua9vCpw==,type:str]
sops:
    age:
        - recipient: age17k7jvvr3vwxugvau3py22vfg08t3r0v9jdh7flrn63fjuw5vmajsymlz0u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOE9hditlQThoRnRZWnlM
            WGdnT1FpRkRGZ3A0OTA2TVdmcVNTelE2eDFVClRXTE1PY2pmRWhBTFpSUDdRelQ5
            SWJKbURCOXBHSmdUVlRmT2VDdC9Hd3cKLS0tIHBvTjIreDNUZ04wT0hDUGxacW4z
            TkYwYTRhaVQ4N1J4RzA4cE94azZYTU0Kv94U4uD2fJlKuZ29pdgfzhlJMIg1aV0W
            5bbYLM8Z2HDXD3fybb9OPf5BCApZJMk1buxopisbXb6bwtye4ClMxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T09:22:23Z"
    mac: ENC[AES256_GCM,data:7/oYb6O9QthFXQNAFcslCJqyd2PiCBe8o/pHBVLO5OpWZL8d3V1/b42ZKs5EHL6fJ8hREM0fMvFB+V/I/dwOUTBkYScFZjJViemNxE3dnpP4QKj+UbZLHr//qokocoPENTF73tjqWul1xICupHRPCTce/vBexMRpnwdjypJRj34=,iv:999bxXhBlLn94/uZNbxMxHuK/r4ocwuvuwvi1CxxO4o=,tag:cvg8Fv20uXvlmIdTMjRH7g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
